### ISSUE TITLE
flux-python 0.61.0

### ISSUE THREAD

**Issue by bryan-garcia** [flux-framework/flux-python#11]
Hello,

Just wanted to report (as suggested in the README) that the flux-python binding on `rzvernal` is not available as of 04/15/24:

```bash
(eos-dg-cache-000) [user@rzvernal10:]$ ./install-flux-python.sh
  __ _                             _   _                 
 / _| |_   ___  __     _ __  _   _| |_| |__   ___  _ __  
| |_| | | | \ \/ /____| '_ \| | | | __| '_ \ / _ \| '_ \ 
|  _| | |_| |>  <_____| |_) | |_| | |_| | | | (_) | | | |
|_| |_|\__,_/_/\_\    | .__/ \__, |\__|_| |_|\___/|_| |_|
                      |_|    |___/               Installer

Report bugs to: https://github.com/flux-framework/flux-python

Flux Python is still being tested, and not all versions are present!
If you need to request a new version added, please open an issue at
the repository above.

⭐️ Checking for install of flux...
Found flux install
commands:               0.61.0
libflux-core:           0.61.0
libflux-security:       0.10.0
build-options:          +ascii-only+systemd+hwloc==2.8.0+zmq==4.3.4

⭐️ Checking for install of python3...
Found python3 install
Python 3.9.12

⭐️ Checking for pip install...
pip 24.0 from /path/to/venv/lib/python3.9/site-packages/pip (python 3.9)

⭐️ Found full version of flux 0.61.0

⭐️ Attempting install of flux-python==0.61.0
python3 -m pip install flux-python==0.61.0
Looking in indexes: https://wci-repo.llnl.gov/repository/pypi-group/simple
ERROR: Could not find a version that satisfies the requirement flux-python==0.61.0 (from versions: 0.46.0rc0, 0.46.0rc1, 0.46.0rc2, 0.47.0rc0, 0.47.0rc1, 0.48.0rc0, 0.48.0rc1, 0.48.0rc2, 0.48.0rc3, 0.48.0rc4, 0.48.0rc5, 0.48.0rc6, 0.49.0rc0, 0.49.0rc1, 0.49.0, 0.50.0rc0, 0.50.0, 0.51.0rc0, 0.51.0, 0.52.0, 0.53.0, 0.54.0, 0.55.0, 0.56.0, 0.57.0, 0.58.0, 0.58.1, 0.59.0rc0, 0.59.0)
ERROR: No matching distribution found for flux-python==0.61.0

```

**Comment by vsoch** [comment]
I can trigger a build for it, will update here when it's done.

**Comment by vsoch** [comment]
Heyo! Apologies for the delay, the pypi upload process seems to have changed a bit. I just pushed a few wheels and source .tar.gz - could you give them a shot? https://pypi.org/project/flux-python/0.61.0/

**Comment by bryan-garcia** [comment]
Everything looks good now! Thanks!

**Comment by vsoch** [comment]
Sure thing, thanks for the notice! The flux versions are moving very quickly these days. Going to close the issue - please re-open or comment if something else comes up.

**Comment by PatrickRMilesLLNL** [comment]
Hello. I'm having a similar issue. The current flux on Vernal is `0.62.0`, but the latest available `flux-python` is only `0.61.0`. Is there a timeline for when `flux-python 0.62.0` will be available?

**Comment by vsoch** [comment]
I'll build it for you!

**Comment by PatrickRMilesLLNL** [comment]
Thank you!!

**Comment by vsoch** [comment]
Give this a try: https://pypi.org/project/flux-python/0.62.0/

**Comment by PatrickRMilesLLNL** [comment]
Problem solved! Thanks for the super quick resolution!

**Comment by bryan-garcia** [comment]
Hi @vsoch , can you build `flux-python 0.63` for `rzadams`?

**Comment by vsoch** [comment]
Coming right up!

**Comment by vsoch** [comment]
Apologies didn't post a follow up - this finished building yesterday. https://pypi.org/project/flux-python/0.63.0/

**Comment by PatrickRMilesLLNL** [comment]
Hi Vanessa. Would you mind building for flux v0.66?

**Comment by vsoch** [comment]
Not at all: https://pypi.org/project/flux-python/0.66.0/

**Comment by PatrickRMilesLLNL** [comment]
Amazing! Thanks!!

**Comment by PatrickRMilesLLNL** [comment]
Hi Vanessa. Could you build for flux v0.68 when you get the chance?

**Comment by PatrickRMilesLLNL** [comment]
Thank you!!
